name: OpenClawWatch
options:
  bundleIdPrefix: com.cryptothaler.mudbug
  deploymentTarget:
    watchOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "6.0"

targets:

  # ──────────────────────────────────────────────
  # Main Watch App (Standalone)
  # ──────────────────────────────────────────────
  OpenClawWatch:
    type: application
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: OpenClawWatch/App/OpenClawApp.swift
      - path: OpenClawWatch/Features/Chat
      - path: OpenClawWatch/Features/Clock
      - path: OpenClawWatch/Core
      - path: OpenClawWatch/Preview Content
        buildPhase: sources

    dependencies:
      - sdk: WatchConnectivity.framework
      - sdk: WatchKit.framework
      - sdk: UserNotifications.framework
      - sdk: AVFoundation.framework

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cryptothaler.mudbug.watchapp
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "6.0"
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: OpenClawWatch/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "20260219"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

    scheme:
      testTargets: []
      gatherCoverageData: false

  # ──────────────────────────────────────────────
  # Widget Extension (Complication)
  # ──────────────────────────────────────────────
  OpenClawWidgetExtension:
    type: app-extension
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: OpenClawWatch/WidgetExtension
        excludes:
          - "Info.plist"
      - path: OpenClawWatch/Core/Models
      - path: OpenClawWatch/Core/Persistence

    dependencies:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cryptothaler.mudbug.watchapp.widget
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: OpenClawWatch/WidgetExtension/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "20260219"

schemes:
  OpenClawWatch:
    build:
      targets:
        OpenClawWatch: all
    run:
      config: Debug
